### ISSUE TITLE
Using JohnSL_Trigger_Rewritten_For_Trinket_usingInternalPullUps

### ISSUE THREAD

**Issue by brendanjerwin** [WingTangWong/AutoTuningFSRTrigger#2]
Does this version eliminate the problem with using 3 different pins for the FSRs?

If it is using the internal pull-ups does that mean that there is no reason for external resistors at all? We can just wire the FSRs right to the pins?

Sorry, been out of it for a while and can't seem to find a clear understanding in the google groups.

**Comment by WingTangWong** [comment]
Even if there are internal pull-ups, it is STRONGLY recommended to employ external pull up resistors.

Part of the reason for this line of logic would be exposure to the stray EMF from the stepper motor wiring, which can induce a voltage against the FSR signal lines as to cause a mis-trigger.  Fairly low chance, but not zero. An explicit external pull up resistor ensures the current is high enough to resist external influences. At least, that is the line of thinking after reading through the Google Groups from that time.  Note, this also depends on the specific circuit/module/FSR/board you are using, so YMMV.
